### ISSUE TITLE
btn-block should have a margin-bottom

### ISSUE THREAD

**Issue by rands0n** [primer/buttons#2]
Looks like the button don't have a margin bottom when they are grouped in vertical. This behavior is not so cool when we have many buttons one below the other.

![screen shot 2016-07-16 at 11 34 08](https://cloud.githubusercontent.com/assets/4191734/16895328/7ce47214-4b49-11e6-9f46-93312496aacc.png)

What do you guys think in add a `margin-bottom` property to separate them? I can make a pull request to fix this.

**Comment by jonrohan** [comment]
We prefer to have the margin separate from these buttons. They're used in such a variety of locations that having margin on them would require more overrides than not. 

What **is** a bug in that screenshot though is the `<p>` should be applying margin there to put space between the blocks.
